# Generated by Django 5.0.6 on 2024-07-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
                ('edition_name', models.CharField(max_length=255)),
                ('initil_submission_date', models.DateTimeField(verbose_name='Data de início de submissão')),
                ('final_submission_date', models.DateTimeField(verbose_name='Data de fim de submissão')),
                ('initial_advisor_date', models.DateTimeField(verbose_name='Data de início de orientação')),
                ('final_advisor_date', models.DateTimeField(verbose_name='Data de fim de orientação')),
                ('initial_evaluators_date', models.DateTimeField(verbose_name='Data de início para avaliadores')),
                ('final_evaluators_date', models.DateTimeField(verbose_name='Data de fim para avaliadores')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('initial_submission_work_date', models.DateTimeField(blank=True, null=True)),
                ('final_submission_work_date', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-title'],
            },
        ),
    ]
