# Generated by Django 5.0.6 on 2024-06-11 17:04

import core.usuario.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
                ('edition_name', models.CharField(max_length=255)),
                ('initil_submission_date', models.DateTimeField(verbose_name='Data de início de submissão')),
                ('final_submission_date', models.DateTimeField(verbose_name='Data de fim de submissão')),
                ('initial_advisor_date', models.DateTimeField(verbose_name='Data de início de orientação')),
                ('final_advisor_date', models.DateTimeField(verbose_name='Data de fim de orientação')),
                ('initial_evaluators_date', models.DateTimeField(verbose_name='Data de início para avaliadores')),
                ('final_evaluators_date', models.DateTimeField(verbose_name='Data de fim para avaliadores')),
                ('banner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('logo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('initial_submission_work_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_submission_work_date', models.DateTimeField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to=settings.AUTH_USER_MODEL)),
                ('co_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.edition')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.field')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_students', models.ForeignKey(limit_choices_to={'user_type': core.usuario.models.Usuario.UserType}, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work')),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(limit_choices_to={'user_type': core.usuario.models.Usuario.UserType}, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('evaluator', models.ForeignKey(limit_choices_to={'is_evaluator': True}, on_delete=django.db.models.deletion.PROTECT, related_name='assessments_evaluator', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(limit_choices_to={'user_type': core.usuario.models.Usuario.UserType}, on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work')),
            ],
        ),
    ]
