# Generated by Django 5.0.6 on 2024-07-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrica_painel', '0001_initial'),
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='evaluator',
            field=models.ForeignKey(limit_choices_to={'is_evaluator': True}, on_delete=django.db.models.deletion.PROTECT, related_name='assessments_evaluator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessments',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edition',
            name='banner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='edition',
            name='logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='advisor',
            field=models.ForeignKey(limit_choices_to={'is_advisor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.edition'),
        ),
        migrations.AddField(
            model_name='work',
            name='field',
            field=models.ManyToManyField(default=None, related_name='fields', to='fabrica_painel.field'),
        ),
        migrations.AddField(
            model_name='work',
            name='ods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.ods'),
        ),
        migrations.AddField(
            model_name='work',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.team'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work'),
        ),
        migrations.AddField(
            model_name='assessments',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.work'),
        ),
    ]
