# Generated by Django 5.0.6 on 2024-07-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Sustainable Goal'),
        ),
        migrations.RemoveField(
            model_name='work',
            name='ods',
        ),
        migrations.AddField(
            model_name='work',
            name='ods',
            field=models.ManyToManyField(default=None, related_name='SustainableGoals', to='fabrica_painel.ods'),
        ),
    ]
