# Generated by Django 5.0.6 on 2024-06-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0002_remove_work_co_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_students',
            new_name='team_student',
        ),
    ]
