# Generated by Django 5.0.6 on 2024-07-05 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0003_rename_team_students_team_team_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='advisor',
            field=models.ForeignKey(limit_choices_to={'is_advisor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='initial_submission_work_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
