# Generated by Django 5.0.6 on 2024-07-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0003_rename_team_students_team_team_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
