# Generated by Django 5.0.6 on 2024-07-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0004_alter_work_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='final_submission_work_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
