# Generated by Django 5.0.6 on 2024-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0004_alter_work_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='reject_submission_work_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
