# Generated by Django 5.0.6 on 2024-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0005_alter_work_final_submission_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
