# Generated by Django 5.0.6 on 2024-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0005_work_reject_submission_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Rejeitado')], default=0),
        ),
    ]
