# Generated by Django 5.0.6 on 2024-07-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0004_alter_assessments_registration'),
        ('fabrica_painel', '0006_work_verification_token'),
    ]

    operations = [
    ]
