# Generated by Django 5.0.6 on 2024-07-11 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0007_merge_20240711_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
