# Generated by Django 5.0.6 on 2024-06-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_painel', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.field'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_advisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_co_supervisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_evaluator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registration',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='Pre_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('registration', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('classroom', models.CharField(max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fabrica_painel.edition')),
            ],
        ),
    ]
