# Generated by Django 5.0.6 on 2024-06-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_cpf_remove_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_co_supervisor',
        ),
    ]
